spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.10/mall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1 # logic delete(deleted 1)
      logic-not-delete-value: 0 # logic delete(not deleted 0)
server:
  port: 10000


