spring:
  cloud:
    gateway:
      routes:
      - id: test_route
        uri: https://www.google.com
        predicates:
         - Query=url,google

      - id: qq_route
        uri: https://www.qq.com
        predicates:
         - Query=url,qq

        ## for product
      - id: product_route
        uri: lb://mall-product
        predicates:
          - Path=/api/product/**
        filters:
          - RewritePath=/api/(?<segment>/?.*), /$\{segment}

        ## from renren-vue, /api
      - id: admin_route
        uri: lb://renren-fast
        predicates:
          - Path=/api/**
        filters:
          - RewritePath=/api/(?<segment>/?.*), /renren-fast/$\{segment}



